### ISSUE TITLE
What's up with `.proxy`?

### ISSUE THREAD

**Issue by soudasuwa** [shroomlife/docker-https-proxy#13]
I can't seem to get my head around why you are adding `.proxy` to `proxyHost`?

https://github.com/shroomlife/docker-https-proxy/blob/a850e706072fea1abc8ccd4ccfffd99dd639e63b/src/proxy.js#L7

The `shroomlife/docker-https-proxy:latest` does not work due to `getaddrinfo ENOTFOUND google.com.proxy`, but building from source with the line above swapped with `host: proxyHost` worked perfectly.

**Comment by shroomlife** [comment]
The reason for adding `.proxy` to `proxyHost` is to create a subdomain that specifies the proxy service. This setup is intended to facilitate easy routing and identification of services within the container environment. Specifically, by appending `.proxy`, we can distinguish proxy-related requests from other types of requests, ensuring that traffic is correctly directed to the proxy service.
